name: ns_eos
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.0
  - jupyter=1.0.0
  - matplotlib=2.2.3
  - numpy=1.15.1
  - pandas=0.23.4
  - nb_conda=2.2.1
  - ipykernel=5.1.0
  - scipy=1.1.0
  - black=19.3b0
  - pytest=4.4.2
  - pytest-runner=4.4
  - pytest-cov=2.6.1
